### ISSUE TITLE
Ch2: Frontend is not working

### ISSUE THREAD

**Issue by vjs1730** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#20] opened 2022-09-26 16:27 UTC
Hi 

Chapter #2 - Frontend is not working. Any suggestion?

![image](https://user-images.githubusercontent.com/6773594/192330689-689bf045-b398-4276-83a8-08145e2acd5a.png)

**Comment by webmakaka** [comment] 2022-10-05 18:09
Hi, try to

replace

https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/blob/6dbdbff76f2b7da531a02e2e8ec3059c12b3056e/ch2/frontend/app.js#L5

on

```
var KC_URL = process.env.KC_URL || 'http://localhost:8080';
```

But, i can't help with next errors with redirects, for now.

**Comment by bjethwan** [comment] 2022-10-11 13:13
I had similar issue and after fixing above, I ran into below issue.
"{"error":"unauthorized_client","error_description":"Client secret not provided in request"}"

**Comment by webmakaka** [comment] 2022-10-12 07:40
@bjethwan 
You can try to do everything from scratch.
I think everything is OK! with frontend.

But you might have error with backend communication with latest KeyCloak versions.

[error access denied](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/14).

**Comment by flowt-au** [comment] 2023-01-11 03:29
Also... if you have already tried to run the Frontend app you will probably need to clear your browser cache after adjusting the URLs as above. The reason is the `<script type="text/javascript" src="KC_URL/js/keycloak.js"></script>` in the index.html file will still try to load the `keycloak.js` file from the /auth folder.

**Comment by stianst** [comment] 2023-02-02 07:39
This issue is caused by breaking changes in recent versions of Keycloak, for more details and how to workaround the issues take a look [here](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26).

I'm closing this issue for now as a duplicate of https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26.

**Closed by stianst** 2023-02-02 07:39 UTC
