### ISSUE TITLE
secured services do not work with keycloak 17

### ISSUE THREAD

**Issue by torstenwerner** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#14] opened 2022-03-18 22:42 UTC
I have followed all steps including the creation of myrole. I have removed the path /auth from all URLs which is needed for keycloak 17. But all invocations of a secured service respond with 'access denied'. They never succeed. I did not find a way to debug the issue.

**Comment by ssaini1175** [comment] 2022-03-21 03:19
I am facing the same issue with using keycloak 17, any recommendations?

**Comment by mezhaka** [comment] 2022-04-06 15:28
The book's setup uses version 12.  Should you rather try it instead?

**Comment by webmakaka** [comment] 2022-10-05 20:39
And what is the solution for getting access to protected route? 
I am always getting an error `'access denied`

```
app.get('/secured', keycloak.protect('realm:myrole'), function (_req, res) {
  res.setHeader('content-type', 'text/plain');
  res.send('Secret message!');
});
```

```
{
  "exp": 1665002578,
  "iat": 1665002278,
  "auth_time": 1664998395,
  "jti": "20fa375a-db21-4025-a245-12080c355dcf",
  "iss": "http://localhost:8080/realms/myrealm",
  "aud": "account",
  "sub": "ea2c2bff-5fab-4613-a28d-4c6e041633a3",
  "typ": "Bearer",
  "azp": "myclient",
  "nonce": "08a67a36-90a1-4f1c-b273-900034cade72",
  "session_state": "b53d17cd-a624-4932-bd9b-00d405cc25c6",
  "acr": "0",
  "allowed-origins": [
    "*"
  ],
  "realm_access": {
    "roles": [
      "default-roles-myrealm",
      "offline_access",
      "uma_authorization",
      "myrole"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "sid": "b53d17cd-a624-4932-bd9b-00d405cc25c6",
  "email_verified": true,
  "name": "XXX",
  "preferred_username": "marley",
  "given_name": "XXX",
  "family_name": "XXX",
  "email": "XXX",
  "picture": "https://avatars.githubusercontent.com/u/10372159?v=4"
}
```

**Comment by webmakaka** [comment] 2022-10-12 08:53
Information how to fix is [here](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/19)

Works with keycloak-19.0.3  by Quarkus

This issue can be closed, i think

**Comment by dub3r** [comment] 2022-10-26 10:59
A gotcha for me was to remember to hard refresh the page (shift+f5) after making the aforementioned changes. Thanks for posting this!

**Comment by stianst** [comment] 2023-02-02 07:39
This issue is caused by breaking changes in recent versions of Keycloak, for more details and how to workaround the issues take a look [here](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26).

I'm closing this issue for now as a duplicate of https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26.

**Closed by stianst** 2023-02-02 07:39 UTC
