### ISSUE TITLE
Adjusting Keycloak URL

### ISSUE THREAD

**Issue by ralfdangel** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#18] opened 2022-06-11 15:02 UTC
Hello,
i use another Keycloak instance which ist running on server from a Hosting Provider. So i want to change standard URL: http://localhost:8080/auth/.....
to my Keycloak URL. But i can`t find the place where to change it.
Can you help me?
Thanks!

**Comment by gruentee** [comment] 2022-08-25 09:16
Do a `grep` for ` KC_URL` which is what the template variable is called in the frontend templates.

**Comment by stianst** [comment] 2023-02-02 07:40
This issue is caused by breaking changes in recent versions of Keycloak, for more details and how to workaround the issues take a look [here](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26).

I'm closing this issue for now as a duplicate of https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26.

**Closed by stianst** 2023-02-02 07:40 UTC
