### ISSUE TITLE
Ch4 urls also wrong in text and sample app

### ISSUE THREAD

**Issue by flowt-au** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#25] opened 2023-01-11 04:15 UTC
As per Ch2: [https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/20](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/20)

**Comment by stianst** [comment] 2023-02-02 07:39
This issue is caused by breaking changes in recent versions of Keycloak, for more details and how to workaround the issues take a look [here](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26).

I'm closing this issue for now as a duplicate of https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26.

**Closed by stianst** 2023-02-02 07:39 UTC
